from blocks import *

CRAFTING_RECIPES = []
# ========== НАЗВАНИЯ ДЛЯ UI ==========
ITEM_NAMES = {
    BLOCK_DIRT: "Земля", BLOCK_GRASS: "Трава", BLOCK_STONE: "Камень", BLOCK_WOOD: "Дерево",
    BLOCK_LEAVES: "Листва", BLOCK_COPPER_ORE: "Медн. руда", BLOCK_IRON_ORE: "Жел. руда",
    BLOCK_GOLD_ORE: "Зол. руда", BLOCK_COAL_ORE: "Угл. руда",
    ITEM_SWORD_WOOD: "Дер. меч", ITEM_SWORD_COPPER: "Медн. меч", ITEM_SWORD_IRON: "Жел. меч",
    ITEM_SWORD_GOLD: "Зол. меч", ITEM_SWORD_DIAMOND: "Алм. меч",
    ITEM_PICKAXE_WOOD: "Дер. кирка", ITEM_PICKAXE_COPPER: "Медн. кирка", ITEM_PICKAXE_IRON: "Жел. кирка",
    ITEM_PICKAXE_GOLD: "Зол. кирка", ITEM_GEL: "Гель", ITEM_COIN: "Монета", ITEM_TORCH: "Факел", ITEM_BONE: "Кость",
    ITEM_COPPER_INGOT: "Медн. слиток", ITEM_IRON_INGOT: "Жел. слиток", ITEM_GOLD_INGOT: "Зол. слиток",
    ITEM_COAL: "Уголь", ITEM_DIAMOND: "Алмаз", ITEM_WOOD_SHIELD: "Дер. щит", BLOCK_TALL_GRASS: "Высокая трава",
    BLOCK_FLOWER_RED: "Красный цветок", BLOCK_FLOWER_YELLOW: "Жёлтый цветок", BLOCK_FLOWER_BLUE: "Синий цветок",
    BLOCK_PLANKS: "Доски", BLOCK_BRICK: "Кирпич", BLOCK_GLASS: "Стекло", BLOCK_SAND: "Песок", BLOCK_SANDSTONE: "Песчаник",
    ITEM_STICK: "Палка", ITEM_LEATHER: "Кожа", ITEM_STRING: "Нить", ITEM_FEATHER: "Перо", ITEM_FLINT: "Кремень",
    ITEM_APPLE: "Яблоко", ITEM_BREAD: "Хлеб", ITEM_COOKED_MEAT: "Жареное мясо",
    ITEM_SWORD_STONE: "Каменный меч", ITEM_PICKAXE_STONE: "Каменная кирка", ITEM_PICKAXE_DIAMOND: "Алмазная кирка",
    BLOCK_SILVER_ORE: "Серебр. руда", BLOCK_PLATINUM_ORE: "Платин. руда",
    BLOCK_MITHRIL_ORE: "Мифр. руда", BLOCK_ADAMANTITE_ORE: "Адамант. руда",
    BLOCK_OBSIDIAN: "Обсидиан", BLOCK_MARBLE: "Мрамор", BLOCK_GLOWSTONE: "Светокамень",
    ITEM_SILVER_INGOT: "Серебр. слиток", ITEM_PLATINUM_INGOT: "Платин. слиток",
    ITEM_MITHRIL_INGOT: "Мифр. слиток", ITEM_ADAMANTITE_INGOT: "Адамант. слиток",
    ITEM_SWORD_SILVER: "Серебр. меч", ITEM_PICKAXE_SILVER: "Серебр. кирка",
    ITEM_SWORD_PLATINUM: "Платин. меч", ITEM_PICKAXE_PLATINUM: "Платин. кирка",
    ITEM_SWORD_MITHRIL: "Мифр. меч", ITEM_PICKAXE_MITHRIL: "Мифр. кирка",
    ITEM_SWORD_ADAMANTITE: "Адамант. меч", ITEM_PICKAXE_ADAMANTITE: "Адамант. кирка",
    BLOCK_FENCE: "Забор", BLOCK_LADDER: "Лестница", BLOCK_ANVIL: "Наковальня",
    BLOCK_FURNACE: "Печь", BLOCK_CHEST: "Сундук", BLOCK_BOOKSHELF: "Книжн. полка",
    BLOCK_SNOW: "Снег", BLOCK_CACTUS: "Кактус", BLOCK_SANDSTONE_SMOOTH: "Глад. песчаник",
    ITEM_PIE: "Пирог", ITEM_SOUP: "Суп", ITEM_MUSHROOM_SOUP: "Гриб. суп", ITEM_COOKED_MUSHROOM: "Жар. гриб",
    ITEM_BOW: "Лук", ITEM_ARROW: "Стрела",
    ITEM_BOOK: "Книга", ITEM_PAPER: "Бумага", ITEM_BOWL: "Миска", ITEM_MUSHROOM: "Гриб", ITEM_WHEAT: "Пшеница",
    BLOCK_TITAN_ORE: "Титановая руда", BLOCK_COBALT_ORE: "Кобальтовая руда",
    BLOCK_NETHERITE_ORE: "Незеритовая руда", BLOCK_CRYSTAL_ORE: "Хрустальная руда",
    ITEM_TITAN_INGOT: "Титановый слиток", ITEM_COBALT_INGOT: "Кобальтовый слиток",
    ITEM_NETHERITE_INGOT: "Незеритовый слиток", ITEM_CRYSTAL_INGOT: "Хрустальный слиток",
    ITEM_SWORD_TITAN: "Титановый меч", ITEM_PICKAXE_TITAN: "Титановая кирка", ITEM_AXE_TITAN: "Титановый топор",
    ITEM_SWORD_COBALT: "Кобальтовый меч", ITEM_PICKAXE_COBALT: "Кобальтовая кирка", ITEM_AXE_COBALT: "Кобальтовый топор",
    ITEM_SWORD_NETHERITE: "Незеритовый меч", ITEM_PICKAXE_NETHERITE: "Незеритовая кирка", ITEM_AXE_NETHERITE: "Незеритовый топор",
    ITEM_SWORD_CRYSTAL: "Хрустальный меч", ITEM_PICKAXE_CRYSTAL: "Хрустальная кирка",
    ITEM_HAMMER: "Молот", ITEM_SPEAR: "Копьё", ITEM_CROSSBOW: "Арбалет",
    ITEM_RUBY: "Рубин", ITEM_SAPPHIRE: "Сапфир", ITEM_EMERALD: "Изумруд",
    ITEM_AMETHYST: "Аметист", ITEM_OPAL: "Опал", ITEM_AMBER: "Янтарь",
    ITEM_PIZZA: "Пицца", ITEM_BURGER: "Бургер", ITEM_SUSHI: "Суши", ITEM_CAKE: "Торт",
    ITEM_SALAD: "Салат", ITEM_FRIED_POTATOES: "Жареная картошка", ITEM_CARROT_JUICE: "Морковный сок",
    ITEM_BANANA: "Банан", ITEM_ORANGE: "Апельсин", ITEM_CARROT: "Морковь",
    ITEM_POTATO: "Картофель", ITEM_TOMATO: "Помидор", ITEM_CUCUMBER: "Огурец",
    ITEM_FISH_PERCH: "Окунь", ITEM_FISH_SALMON: "Лосось", ITEM_FISH_GOLDFISH: "Золотая рыбка",
    ITEM_FISHING_ROD: "Удочка", ITEM_BAIT: "Наживка",
    BLOCK_DOOR: "Дверь", BLOCK_WINDOW: "Окно", BLOCK_SHUTTER: "Ставни",
    BLOCK_PILLAR: "Колонна", BLOCK_STATUE: "Статуя", BLOCK_CARPET: "Ковёр",
    BLOCK_PAINTING: "Картина", BLOCK_FRAME: "Рамка", BLOCK_SHELF: "Полка",
    BLOCK_BUSH: "Куст", BLOCK_FERN: "Папоротник", BLOCK_VINE: "Лиана",
    BLOCK_TULIP_RED: "Красный тюльпан", BLOCK_TULIP_YELLOW: "Жёлтый тюльпан", BLOCK_DAISY: "Ромашка",
    ITEM_GUITAR: "Гитара", ITEM_FLUTE: "Флейта", ITEM_DRUM: "Барабан", ITEM_HARP: "Арфа",
    ITEM_HOE: "Мотыга", ITEM_WATERING_CAN: "Лейка", ITEM_FERTILIZER: "Удобрение",
    ITEM_LEATHER_STRIP: "Кожаная полоса", ITEM_SCALE: "Чешуя", ITEM_SHELL: "Панцирь",
    ITEM_FEATHER_BLUE: "Синее перо", ITEM_FEATHER_RED: "Красное перо", ITEM_FEATHER_GREEN: "Зелёное перо",
    ITEM_BONE_MEAL: "Костная мука", ITEM_WOOL: "Шерсть",
    ITEM_SPELLBOOK_FIRE: "Книга огня", ITEM_SPELLBOOK_ICE: "Книга льда",
    ITEM_SPELLBOOK_HEAL: "Книга лечения", ITEM_SPELLBOOK_TELEPORT: "Книга телепортации",
}

# ---- Уникальные рецепты ----
CRAFTING_RECIPES.extend([
    ({'type': ITEM_TORCH, 'count': 4}, [(BLOCK_WOOD, 1), (ITEM_COAL, 1)]),
    ({'type': ITEM_SWORD_WOOD, 'count': 1}, [(BLOCK_WOOD, 7)]),
    ({'type': ITEM_PICKAXE_WOOD, 'count': 1}, [(BLOCK_WOOD, 5)]),
    ({'type': ITEM_WOOD_SHIELD, 'count': 1}, [(BLOCK_WOOD, 10), (ITEM_BONE, 2)]),
    ({'type': ITEM_STICK, 'count': 4}, [(BLOCK_WOOD, 2)]),
    ({'type': BLOCK_PLANKS, 'count': 4}, [(BLOCK_WOOD, 1)]),
    ({'type': ITEM_SWORD_STONE, 'count': 1}, [(BLOCK_STONE, 2), (ITEM_STICK, 1)]),
    ({'type': ITEM_PICKAXE_STONE, 'count': 1}, [(BLOCK_STONE, 3), (ITEM_STICK, 2)]),
    ({'type': ITEM_PICKAXE_DIAMOND, 'count': 1}, [(ITEM_DIAMOND, 3), (ITEM_STICK, 2)]),
    ({'type': BLOCK_GLASS, 'count': 1}, [(BLOCK_SAND, 1)]),
    ({'type': BLOCK_BRICK, 'count': 1}, [(BLOCK_STONE, 4)]),
    ({'type': BLOCK_SANDSTONE, 'count': 1}, [(BLOCK_SAND, 2)]),
    ({'type': ITEM_APPLE, 'count': 1}, [(BLOCK_LEAVES, 3)]),
    ({'type': ITEM_BREAD, 'count': 1}, [(ITEM_APPLE, 2), (ITEM_GEL, 1)]),
    ({'type': ITEM_COOKED_MEAT, 'count': 1}, [(ITEM_GEL, 3), (ITEM_COAL, 1)]),
    ({'type': BLOCK_FENCE, 'count': 8}, [(BLOCK_WOOD, 2), (ITEM_STICK, 4)]),
    ({'type': BLOCK_LADDER, 'count': 6}, [(BLOCK_WOOD, 3)]),
    ({'type': BLOCK_ANVIL, 'count': 1}, [(ITEM_IRON_INGOT, 6)]),
    ({'type': BLOCK_FURNACE, 'count': 1}, [(BLOCK_STONE, 8), (ITEM_COAL, 1)]),
    ({'type': BLOCK_CHEST, 'count': 1}, [(BLOCK_WOOD, 8)]),
    ({'type': BLOCK_BOOKSHELF, 'count': 1}, [(BLOCK_WOOD, 6), (ITEM_BOOK, 3)]),
    ({'type': BLOCK_SNOW, 'count': 4}, [(BLOCK_GRASS, 1)]),
    ({'type': BLOCK_SANDSTONE_SMOOTH, 'count': 1}, [(BLOCK_SANDSTONE, 1)]),
    ({'type': BLOCK_OBSIDIAN, 'count': 1}, [(BLOCK_STONE, 2), (ITEM_COAL, 1)]),
    ({'type': BLOCK_GLOWSTONE, 'count': 1}, [(BLOCK_GLASS, 1), (ITEM_COAL, 1)]),
    ({'type': ITEM_PIE, 'count': 1}, [(ITEM_APPLE, 3), (ITEM_GEL, 2), (ITEM_WHEAT, 2)]),
    ({'type': ITEM_SOUP, 'count': 1}, [(ITEM_APPLE, 2), (ITEM_GEL, 1), (ITEM_BOWL, 1)]),
    ({'type': ITEM_MUSHROOM_SOUP, 'count': 1}, [(ITEM_MUSHROOM, 2), (ITEM_BOWL, 1)]),
    ({'type': ITEM_COOKED_MUSHROOM, 'count': 1}, [(ITEM_MUSHROOM, 1), (ITEM_COAL, 1)]),
    ({'type': ITEM_BOW, 'count': 1}, [(ITEM_STICK, 3), (ITEM_STRING, 3)]),
    ({'type': ITEM_ARROW, 'count': 8}, [(ITEM_STICK, 1), (ITEM_FEATHER, 1), (ITEM_FLINT, 1)]),
    ({'type': ITEM_PAPER, 'count': 3}, [(BLOCK_WOOD, 1)]),
    ({'type': ITEM_BOOK, 'count': 1}, [(ITEM_LEATHER, 1), (ITEM_FEATHER, 2), (ITEM_PAPER, 3)]),
    ({'type': ITEM_TORCH, 'count': 8}, [(ITEM_STICK, 1), (BLOCK_GLOWSTONE, 1)]),
    ({'type': ITEM_HAMMER, 'count': 1}, [(ITEM_IRON_INGOT, 10), (BLOCK_WOOD, 2)]),
    ({'type': ITEM_SPEAR, 'count': 1}, [(ITEM_IRON_INGOT, 6), (ITEM_STICK, 3)]),
    ({'type': ITEM_CROSSBOW, 'count': 1}, [(ITEM_IRON_INGOT, 4), (ITEM_STICK, 2), (ITEM_STRING, 2)]),
    ({'type': ITEM_RUBY, 'count': 1}, [(ITEM_COPPER_INGOT, 2), (ITEM_GEL, 1)]),
    ({'type': ITEM_SAPPHIRE, 'count': 1}, [(ITEM_IRON_INGOT, 2), (ITEM_GEL, 1)]),
    ({'type': ITEM_EMERALD, 'count': 1}, [(ITEM_GOLD_INGOT, 2), (ITEM_APPLE, 1)]),
    ({'type': ITEM_AMETHYST, 'count': 1}, [(ITEM_SILVER_INGOT, 2), (ITEM_GEL, 2)]),
    ({'type': ITEM_OPAL, 'count': 1}, [(ITEM_PLATINUM_INGOT, 2), (ITEM_GEL, 2)]),
    ({'type': ITEM_AMBER, 'count': 1}, [(ITEM_GOLD_INGOT, 2), (ITEM_GEL, 3)]),
    ({'type': ITEM_PIZZA, 'count': 1}, [(ITEM_WHEAT, 2), (ITEM_TOMATO, 2), (ITEM_GEL, 1)]),
    ({'type': ITEM_BURGER, 'count': 1}, [(ITEM_WHEAT, 2), (ITEM_COOKED_MEAT, 1), (ITEM_TOMATO, 1)]),
    ({'type': ITEM_SUSHI, 'count': 1}, [(ITEM_FISH_SALMON, 2), (ITEM_WHEAT, 1)]),
    ({'type': ITEM_CAKE, 'count': 1}, [(ITEM_WHEAT, 3), (ITEM_APPLE, 2), (ITEM_GEL, 2)]),
    ({'type': ITEM_SALAD, 'count': 1}, [(ITEM_CARROT, 2), (ITEM_CUCUMBER, 2), (ITEM_TOMATO, 1)]),
    ({'type': ITEM_FRIED_POTATOES, 'count': 1}, [(ITEM_POTATO, 3), (ITEM_COAL, 1)]),
    ({'type': ITEM_CARROT_JUICE, 'count': 1}, [(ITEM_CARROT, 3), (ITEM_GEL, 1)]),
    ({'type': ITEM_BANANA, 'count': 1}, [(ITEM_APPLE, 1), (ITEM_GEL, 1)]),
    ({'type': ITEM_ORANGE, 'count': 1}, [(ITEM_APPLE, 1), (ITEM_GEL, 1)]),
    ({'type': ITEM_CARROT, 'count': 2}, [(BLOCK_GRASS, 1)]),
    ({'type': ITEM_POTATO, 'count': 2}, [(BLOCK_DIRT, 1)]),
    ({'type': ITEM_TOMATO, 'count': 2}, [(ITEM_APPLE, 1), (ITEM_GEL, 1)]),
    ({'type': ITEM_CUCUMBER, 'count': 2}, [(ITEM_APPLE, 1), (ITEM_WATERING_CAN, 1)]),
    ({'type': ITEM_FISH_PERCH, 'count': 1}, [(ITEM_GEL, 2), (ITEM_APPLE, 1)]),
    ({'type': ITEM_FISH_SALMON, 'count': 1}, [(ITEM_GEL, 3), (ITEM_ORANGE, 1)]),
    ({'type': ITEM_FISH_GOLDFISH, 'count': 1}, [(ITEM_GOLD_INGOT, 1), (ITEM_GEL, 1)]),
    ({'type': ITEM_FISHING_ROD, 'count': 1}, [(ITEM_STICK, 2), (ITEM_STRING, 2)]),
    ({'type': ITEM_BAIT, 'count': 4}, [(ITEM_GEL, 1)]),
    ({'type': BLOCK_DOOR, 'count': 1}, [(BLOCK_WOOD, 6)]),
    ({'type': BLOCK_WINDOW, 'count': 1}, [(BLOCK_GLASS, 4), (BLOCK_WOOD, 2)]),
    ({'type': BLOCK_SHUTTER, 'count': 1}, [(BLOCK_WOOD, 4)]),
    ({'type': BLOCK_PILLAR, 'count': 1}, [(BLOCK_STONE, 4)]),
    ({'type': BLOCK_STATUE, 'count': 1}, [(BLOCK_STONE, 6), (ITEM_GOLD_INGOT, 1)]),
    ({'type': BLOCK_CARPET, 'count': 1}, [(ITEM_WOOL, 4)]),
    ({'type': BLOCK_PAINTING, 'count': 1}, [(BLOCK_WOOD, 2), (ITEM_WOOL, 1), (ITEM_GEL, 1)]),
    ({'type': BLOCK_FRAME, 'count': 1}, [(BLOCK_WOOD, 2), (BLOCK_GLASS, 1)]),
    ({'type': BLOCK_SHELF, 'count': 1}, [(BLOCK_WOOD, 3)]),
    ({'type': BLOCK_BUSH, 'count': 1}, [(BLOCK_LEAVES, 2)]),
    ({'type': BLOCK_FERN, 'count': 1}, [(BLOCK_GRASS, 1), (ITEM_GEL, 1)]),
    ({'type': BLOCK_VINE, 'count': 2}, [(BLOCK_LEAVES, 1), (ITEM_STRING, 1)]),
    ({'type': BLOCK_TULIP_RED, 'count': 1}, [(BLOCK_FLOWER_RED, 1), (ITEM_GEL, 1)]),
    ({'type': BLOCK_TULIP_YELLOW, 'count': 1}, [(BLOCK_FLOWER_YELLOW, 1), (ITEM_GEL, 1)]),
    ({'type': BLOCK_DAISY, 'count': 1}, [(BLOCK_FLOWER_RED, 1), (BLOCK_FLOWER_YELLOW, 1)]),
    ({'type': ITEM_GUITAR, 'count': 1}, [(BLOCK_WOOD, 4), (ITEM_STRING, 3)]),
    ({'type': ITEM_FLUTE, 'count': 1}, [(ITEM_STICK, 4), (ITEM_GOLD_INGOT, 1)]),
    ({'type': ITEM_DRUM, 'count': 1}, [(BLOCK_WOOD, 3), (ITEM_LEATHER, 2)]),
    ({'type': ITEM_HARP, 'count': 1}, [(BLOCK_WOOD, 5), (ITEM_STRING, 4)]),
    ({'type': ITEM_HOE, 'count': 1}, [(ITEM_IRON_INGOT, 2), (ITEM_STICK, 1)]),
    ({'type': ITEM_WATERING_CAN, 'count': 1}, [(ITEM_IRON_INGOT, 3), (ITEM_GEL, 2)]),
    ({'type': ITEM_FERTILIZER, 'count': 2}, [(ITEM_BONE_MEAL, 1), (ITEM_GEL, 1)]),
    ({'type': ITEM_LEATHER_STRIP, 'count': 2}, [(ITEM_LEATHER, 1)]),
    ({'type': ITEM_SCALE, 'count': 1}, [(ITEM_FISH_SALMON, 1), (ITEM_IRON_INGOT, 1)]),
    ({'type': ITEM_SHELL, 'count': 1}, [(ITEM_FISH_SALMON, 1), (BLOCK_STONE, 1)]),
    ({'type': ITEM_FEATHER_BLUE, 'count': 1}, [(ITEM_FEATHER, 1), (ITEM_SAPPHIRE, 1)]),
    ({'type': ITEM_FEATHER_RED, 'count': 1}, [(ITEM_FEATHER, 1), (ITEM_RUBY, 1)]),
    ({'type': ITEM_FEATHER_GREEN, 'count': 1}, [(ITEM_FEATHER, 1), (ITEM_EMERALD, 1)]),
    ({'type': ITEM_BONE_MEAL, 'count': 2}, [(ITEM_BONE, 1)]),
    ({'type': ITEM_WOOL, 'count': 2}, [(ITEM_STRING, 2)]),
    ({'type': ITEM_SPELLBOOK_FIRE, 'count': 1}, [(ITEM_BOOK, 1), (ITEM_RUBY, 3)]),
    ({'type': ITEM_SPELLBOOK_ICE, 'count': 1}, [(ITEM_BOOK, 1), (ITEM_SAPPHIRE, 3)]),
    ({'type': ITEM_SPELLBOOK_HEAL, 'count': 1}, [(ITEM_BOOK, 1), (ITEM_EMERALD, 3)]),
    ({'type': ITEM_SPELLBOOK_TELEPORT, 'count': 1}, [(ITEM_BOOK, 1), (ITEM_AMETHYST, 3)]),
])

# ---- Автоматическая генерация для руд и инструментов ----
ORE_TO_INGOT = {
    BLOCK_COPPER_ORE: ITEM_COPPER_INGOT,
    BLOCK_IRON_ORE: ITEM_IRON_INGOT,
    BLOCK_GOLD_ORE: ITEM_GOLD_INGOT,
    BLOCK_SILVER_ORE: ITEM_SILVER_INGOT,
    BLOCK_PLATINUM_ORE: ITEM_PLATINUM_INGOT,
    BLOCK_MITHRIL_ORE: ITEM_MITHRIL_INGOT,
    BLOCK_ADAMANTITE_ORE: ITEM_ADAMANTITE_INGOT,
    BLOCK_TITAN_ORE: ITEM_TITAN_INGOT,
    BLOCK_COBALT_ORE: ITEM_COBALT_INGOT,
    BLOCK_NETHERITE_ORE: ITEM_NETHERITE_INGOT,
    BLOCK_CRYSTAL_ORE: ITEM_CRYSTAL_INGOT,
}

for ore, ingot in ORE_TO_INGOT.items():
    CRAFTING_RECIPES.append(({'type': ingot, 'count': 1}, [(ore, 3)]))

TOOL_RECIPES = [
    (ITEM_COPPER_INGOT, 5, 4, 0),
    (ITEM_IRON_INGOT, 8, 5, 0),
    (ITEM_GOLD_INGOT, 8, 5, 0),
    (ITEM_SILVER_INGOT, 6, 4, 0),
    (ITEM_PLATINUM_INGOT, 8, 5, 0),
    (ITEM_MITHRIL_INGOT, 10, 6, 0),
    (ITEM_ADAMANTITE_INGOT, 12, 7, 0),
    (ITEM_TITAN_INGOT, 8, 5, 6),
    (ITEM_COBALT_INGOT, 8, 5, 6),
    (ITEM_NETHERITE_INGOT, 10, 6, 7),
    (ITEM_CRYSTAL_INGOT, 6, 4, 0),
]

TOOL_IDS = {
    ITEM_COPPER_INGOT: (ITEM_SWORD_COPPER, ITEM_PICKAXE_COPPER, None),
    ITEM_IRON_INGOT: (ITEM_SWORD_IRON, ITEM_PICKAXE_IRON, None),
    ITEM_GOLD_INGOT: (ITEM_SWORD_GOLD, ITEM_PICKAXE_GOLD, None),
    ITEM_SILVER_INGOT: (ITEM_SWORD_SILVER, ITEM_PICKAXE_SILVER, None),
    ITEM_PLATINUM_INGOT: (ITEM_SWORD_PLATINUM, ITEM_PICKAXE_PLATINUM, None),
    ITEM_MITHRIL_INGOT: (ITEM_SWORD_MITHRIL, ITEM_PICKAXE_MITHRIL, None),
    ITEM_ADAMANTITE_INGOT: (ITEM_SWORD_ADAMANTITE, ITEM_PICKAXE_ADAMANTITE, None),
    ITEM_TITAN_INGOT: (ITEM_SWORD_TITAN, ITEM_PICKAXE_TITAN, ITEM_AXE_TITAN),
    ITEM_COBALT_INGOT: (ITEM_SWORD_COBALT, ITEM_PICKAXE_COBALT, ITEM_AXE_COBALT),
    ITEM_NETHERITE_INGOT: (ITEM_SWORD_NETHERITE, ITEM_PICKAXE_NETHERITE, ITEM_AXE_NETHERITE),
    ITEM_CRYSTAL_INGOT: (ITEM_SWORD_CRYSTAL, ITEM_PICKAXE_CRYSTAL, None),
}

for ingot, sword_qty, pick_qty, axe_qty in TOOL_RECIPES:
    sword_id, pick_id, axe_id = TOOL_IDS[ingot]
    if sword_id and sword_qty > 0:
        CRAFTING_RECIPES.append(({'type': sword_id, 'count': 1}, [(ingot, sword_qty), (BLOCK_WOOD, 2)]))
    if pick_id and pick_qty > 0:
        CRAFTING_RECIPES.append(({'type': pick_id, 'count': 1}, [(ingot, pick_qty), (BLOCK_WOOD, 2)]))
    if axe_id and axe_qty > 0:
        CRAFTING_RECIPES.append(({'type': axe_id, 'count': 1}, [(ingot, axe_qty), (BLOCK_WOOD, 2)]))